# Generated by Django 4.1.1 on 2022-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('coupon', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('queue', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
